version: '3.8'

services:
  git-sync:
    image: k8s.gcr.io/git-sync/git-sync:v3.6.1
    container_name: framerate-git-sync
    environment:
      GIT_SYNC_REPO: "https://github.com/buildcores/buildcores-open-db.git"
      GIT_SYNC_BRANCH: "main"
      GIT_SYNC_ROOT: "/tmp/git"
      GIT_SYNC_DEST: "opendb"
      GIT_SYNC_WAIT: "60"
    volumes:
      - opendb_data:/tmp/git
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "[ -f /tmp/git/opendb/.git/HEAD ]"]
      interval: 1m
      timeout: 10s
      retries: 3
    restart: always

volumes:
  opendb_data:
    driver: local
