/* Translations generated by AI */
export type Lang = "es" | "en" | "arn";

export const dictionaries: Record<Lang, Record<string, string>> = {
  es: {
    // Specs
    manufacturer: "Fabricante",
    chipset_manufacturer: "Fabricante del Chipset",
    chipset: "Chipset",
    architecture: "Arquitectura",
    memory_gb: "Memoria (GB)",
    memory_type: "Tipo de Memoria",
    core_base_clock_mhz: "Reloj Base (MHz)",
    core_boost_clock_mhz: "Reloj Boost (MHz)",
    core_count: "Núcleos",
    memory_clock_mhz: "Reloj Memoria (MHz)",
    memory_bus_bit: "Bus de Memoria (bit)",
    interface: "Interfaz",
    length_mm: "Largo (mm)",
    tdp_w: "TDP (W)",
    cooling: "Refrigeración",
    slots: "Ranuras",
    frame_sync: "Sincronización de Cuadros",
    color: "Color",
    power_connectors: "Conectores de Poder",
    video_ports: "Puertos de Video",
    series: "Serie",
    microarchitecture: "Microarquitectura",
    socket: "Socket",
    cores: "Núcleos",
    clocks: "Frecuencias",
    cache: "Caché",
    integrated_graphics: "Gráficos Integrados",
    includes_cooler: "Incluye Cooler",
    ecc_support: "Soporte ECC",
    lithography: "Litografía",
    max_memory_gb: "Memoria Máxima (GB)",
    memory_types: "Tipos de Memoria",
    wattage: "Potencia (W)",
    form_factor: "Factor de Forma",
    efficiency_rating: "Certificación de Eficiencia",
    modular: "Modular",
    fanless: "Fanless",
    connectors: "Conectores",
    pcie_slots: "Ranuras PCIe",
    m2_slots: "Ranuras M.2",
    sata_ports: "Puertos SATA",
    onboard_ethernet: "Ethernet Integrado",
    wireless_networking: "Red Inalámbrica",
    usb_headers: "Cabezales USB",
    supported_motherboard_form_factors: "Factores de Forma Soportados",
    side_panel: "Panel Lateral",
    max_gpu_length_mm: "Largo Máx. GPU (mm)",
    max_cpu_cooler_height_mm: "Altura Máx. CPU Cooler (mm)",
    drive_bays: "Bahías de Unidad",
    expansion_slots: "Ranuras de Expansión",
    front_ports: "Puertos Frontales",
    included_fans: "Ventiladores Incluidos",
    speed_mt_s: "Velocidad (MT/s)",
    modules: "Módulos",
    total_capacity_gb: "Capacidad Total (GB)",
    cas_latency: "Latencia CAS",
    timings: "Timings",
    voltage: "Voltaje",
    heat_spreader: "Disipador",
    rgb: "RGB",
    capacity_gb: "Capacidad (GB)",
    rpm: "RPM",
    nvme: "NVMe",
    read_speed_mb_s: "Velocidad Lectura (MB/s)",
    write_speed_mb_s: "Velocidad Escritura (MB/s)",
    size_mm: "Tamaño (mm)",
    quantity: "Cantidad",
    airflow_cfm: "Flujo de Aire (CFM)",
    noise_level_db: "Nivel de Ruido (dB)",
    pwm: "PWM",
    static_pressure_mmh2o: "Presión Estática (mmH2O)",
    water_cooled: "Refrigeración Líquida",
    radiator_size_mm: "Tamaño Radiador (mm)",
    fan_size_mm: "Tamaño Ventilador (mm)",
    sockets: "Sockets",
    memory: "Memoria",
    type: "Tipo",
    max_gb: "Máx (GB)",
    key: "Llave",
    size: "Tamaño",
    gen: "Gen",
    lanes: "Lanes",
    usb_4: "USB4",
    usb_2_0: "USB 2.0",
    usb_3_2_gen_1: "USB 3.2 Gen 1",
    usb_3_2_gen_2: "USB 3.2 Gen 2",
    usb_3_2_gen_2x2: "USB 3.2 Gen 2x2",

    // UI (Product Page)
    best_price_cash: "Mejor Precio Efectivo",
    available_in_stores: "Disponible en {count} tiendas",
    go_to_store: "Ir a Tienda",
    price_history: "Historial de precios",
    price_history_window: "Últimos {days} días",
    price_history_min: "Mínimo en el período:",
    price_history_empty: "Aún no hay suficientes datos para mostrar la evolución de precios.",
    create_alert: "Crear alerta",
    best_current_offer: "Mejor oferta actual",
    other_versions: "Otras versiones disponibles",
    store_comparison: "Precios por tienda",
    store: "Tienda",
    price: "Precio",
    cash: "Efectivo",
    normal: "Normal",
    action: "Acción",
    see_offer: "Ver Oferta",
    specs: "Especificaciones",
    specs_title: "Especificaciones Técnicas",
    check_stock: "Consultar stock",
    in_stock: "En Stock",
    home: "Inicio",
    product_not_found: "Producto no encontrado",
    generic: "Genérico",
    yes: "Sí",
    no: "No",

    // Preferences
    preferences: "Preferencias",
    preferences_desc: "Personaliza tu experiencia en la aplicación.",
    visualization: "Visualización",
    choose_theme: "Elige tu interfaz preferida.",
    system: "Sistema",
    light: "Claro",
    dark: "Oscuro",
    language: "Idioma",
    select_language: "Selecciona el idioma de la interfaz.",
    translation_beta_title: "Traducción en beta",
    translation_beta_desc:
      "Esta traducción es preliminar y puede contener errores. ¿Encontraste algo que mejorar? Ayúdanos enviando una sugerencia.",
    suggest_correction: "Sugerir corrección",
    feedback_dialog_title: "Sugiere una corrección de traducción",
    feedback_dialog_desc: "Elige un texto y propón una mejor versión. Tu sugerencia será revisada antes de aplicarse.",
    feedback_search_placeholder: "Buscar por clave o texto...",
    feedback_no_matches: "Sin resultados.",
    feedback_change: "cambiar",
    feedback_your_suggestion: "Tu sugerencia",
    feedback_suggestion_placeholder: "Propón una mejor traducción...",
    feedback_comment: "Comentario",
    feedback_optional: "(opcional)",
    feedback_comment_placeholder: "¿Por qué es mejor? Fuente / matiz...",
    feedback_send: "Enviar sugerencia",
    feedback_sending: "Enviando...",
    feedback_sent: "¡Gracias! Tu sugerencia fue enviada.",
    feedback_send_error: "No se pudo enviar el feedback. Intenta más tarde.",
    feedback_empty_error: "La sugerencia no puede estar vacía",
    feedback_same_error: "La sugerencia debe ser distinta al texto actual",
    feedback_showing_some: "Mostrando 100 de {total}. Refina tu búsqueda.",
    feedback_current: "actual",
    feedback_empty_value: "(vacío)",
    feedback_close: "Cerrar",

    // Profile page
    profile_joined: "Se unió en {date}",
    profile_quotes_title_owner: "Mis cotizaciones",
    profile_quotes_title_other: "Cotizaciones de {name}",
    profile_quotes_count_owner: "{count} cotización(es) creada(s)",
    profile_quotes_count_other: "{count} cotización(es) pública(s)",
    profile_no_quotes_owner: "No tienes cotizaciones aún",
    profile_no_quotes_other: "Este usuario no tiene cotizaciones públicas",
    profile_no_quotes_owner_cta: "Crea tu primera cotización para empezar a armar el PC de tus sueños.",
    profile_components_count: "{count} componentes",
    profile_default_name: "Usuario",
    profile_back_home: "Volver al inicio",
    profile_not_found_title: "Usuario no encontrado",
    profile_not_found_desc: "El perfil que buscas no existe o ha sido eliminado.",
    profile_load_error_title: "Error al cargar el perfil",
    profile_load_error_desc: "Hubo un problema al obtener los datos del usuario.",
    profile_unexpected_error: "Ha ocurrido un error inesperado.",
    profile_try_again: "Por favor intenta nuevamente más tarde.",
    profile_edit: "Editar perfil",
    profile_share: "Compartir perfil",
    profile_share_copied: "Enlace copiado al portapapeles",

    // Navbar
    explore: "Explorar",
    hardware: "Hardware",
    create_quote: "Crear Cotización",
    search: "Buscador",
    user: "Usuario",
    profile: "Perfil",
    settings: "Ajustes",
    logout: "Cerrar sesión",
    login: "Entrar",
    login_desc: "Elige un proveedor para crear tu cuenta o iniciar sesión",
    continue_with: "Continuar con {provider}",
    terms: "Términos",
    privacy: "Privacidad",
    legal_text: "Al continuar, aceptas nuestros {terms} y {privacy}",
    no_categories: "No hay categorías disponibles",

    // Greetings (Morning)
    greeting_morning_1: "¿Café o pasta térmica para desayunar?",
    greeting_morning_2: "Los precios bajaron más rápido que tú de la cama",
    greeting_morning_3: "Buen día, hoy sí sale ese procesador",
    greeting_morning_4: "Menos lag y más café para empezar",
    greeting_morning_5: "El que madruga, encuentra stock",

    // Greetings (Afternoon)
    greeting_afternoon_1: "Mirar hardware también cuenta como trabajar",
    greeting_afternoon_2: "Tu jefe no está mirando, busca esa GPU",
    greeting_afternoon_3: "¿Otro ventilador? Nunca es suficiente",
    greeting_afternoon_4: "El hambre pasa, los FPS son para siempre",
    greeting_afternoon_5: "Solo una pieza más y juro que termino el build",

    // Greetings (Evening)
    greeting_evening_1: "Prende el RGB que ya oscureció",
    greeting_evening_2: "¿Tu PC brilla más que tu futuro? El mío sí",
    greeting_evening_3: "Hora de los FPS altos y los precios bajos",
    greeting_evening_4: "No es un gasto, es una inversión en felicidad",
    greeting_evening_5: "Configurando el setup para ganar hoy",

    // Greetings (Night)
    greeting_night_1: "La luz del monitor cuenta como vitamina D",
    greeting_night_2: "Dormir es para gente con PCs lentas",
    greeting_night_3: "Tu cuenta bancaria dice no, pero tu build dice sí",
    greeting_night_4: "Un ojo en el código y otro en esa oferta",
    greeting_night_5: "Mañana ese precio será historia, cómpralo ya",

    // Home
    popular_products: "Productos populares",
    popular_products_desc: "Los productos más vistos por la comunidad",
    view_all: "Ver todos",
    no_products: "No hay productos disponibles",
    recent_offers: "Ofertas recientes",
    recent_offers_desc: "Productos con bajadas de precio",

    // Add to quote
    add_to_quote: "Agregar a cotización",
    login_to_save_quote_title: "Inicia sesión para guardar",
    login_to_save_quote_desc: "Crea cotizaciones para comparar PCs y guardar tus armados favoritos.",
    select_quote: "Seleccionar cotización",
    no_quotes: "No tienes cotizaciones creadas",
    create_new: "Crear nueva",
    confirm: "Confirmar",
    product_added: "Producto agregado a la cotización {name}",
    select_option: "Seleccionar...",

    // Create Quote Dialog
    create_new_quote_title: "Crear nueva cotización",
    create_quote_desc: "Dale un nombre a tu proyecto para empezar a agregar componentes.",
    create_quote_error: "Error al crear la cotización",
    name: "Nombre",
    quote_name_placeholder: "Ej: PC Gamer 2026",
    description_optional: "Descripción (Opcional)",
    quote_description_placeholder: "Para qué usarás este PC...",
    public_quote: "Cotizacion pública",
    cancel: "Cancelar",

    // Settings Layout
    account: "Cuenta",

    // Account Settings
    your_profile: "Tu perfil",
    profile_desc: "Elige cómo apareces como anfitrión o invitado.",
    full_name: "Nombre completo",
    full_name_placeholder: "Tu nombre",
    username: "Nombre de usuario",
    bio_label: "Biografía",
    bio_coming_soon: "Biografía (Próximamente)",
    bio_placeholder: "Comparte un poco sobre tu experiencia e intereses.",
    saving: "Guardando...",
    save_changes: "Guardar cambios",
    emails: "Correos",
    emails_desc: "Gestiona tus direcciones de correo electrónico.",
    primary_email: "Email principal",
    managed_by_provider: "Gestionado por el proveedor de autenticación",
    manage: "Gestionar",
    saving_changes_toast: "Guardando cambios...",
    profile_updated_toast: "Perfil actualizado correctamente",
    profile_update_error_toast: "Error al actualizar el perfil",

    // Quote Details
    by: "Por {name}",
    updated_on: "Actualizado el {date}",
    estimated_wattage: "Consumo Estimado",
    components: "Componentes",
    active_items_count: "{count} activos",
    price_normal: "Precio Normal",
    price_cash: "Precio Efectivo",
    others: "Otros",
    some_items_out_of_stock: "Algunos productos no tienen stock disponible. El total puede variar.",
    total_normal: "Total Normal",
    total_cash: "Total Efectivo",

    // Quote Actions / Messages
    quote_not_found: "cotizacion no encontrada",
    product_removed: "Producto eliminado",
    quote_deleted: "Cotización eliminada correctamente",
    quote_delete_error: "Error al eliminar la cotización",
    product_added_short: "Producto agregado",
    product_add_error: "Error al agregar producto",
    compatibility_checked: "Compatibilidad verificada",
    compatibility_check_error: "Error al verificar compatibilidad",
    removing_product: "Eliminando producto...",
    remove_product_error: "Error al eliminar producto",
  },
  en: {
    // Specs
    manufacturer: "Manufacturer",
    chipset_manufacturer: "Chipset Manufacturer",
    chipset: "Chipset",
    architecture: "Architecture",
    memory_gb: "Memory (GB)",
    memory_type: "Memory Type",
    core_base_clock_mhz: "Core Base Clock (MHz)",
    core_boost_clock_mhz: "Core Boost Clock (MHz)",
    core_count: "Core Count",
    memory_clock_mhz: "Memory Clock (MHz)",
    memory_bus_bit: "Memory Bus (bit)",
    interface: "Interface",
    length_mm: "Length (mm)",
    tdp_w: "TDP (W)",
    cooling: "Cooling",
    slots: "Slots",
    frame_sync: "Frame Sync",
    color: "Color",
    power_connectors: "Power Connectors",
    video_ports: "Video Ports",
    series: "Series",
    microarchitecture: "Microarchitecture",
    socket: "Socket",
    cores: "Cores",
    clocks: "Clocks",
    cache: "Cache",
    integrated_graphics: "Integrated Graphics",
    includes_cooler: "Includes Cooler",
    ecc_support: "ECC Support",
    lithography: "Lithography",
    max_memory_gb: "Max Memory (GB)",
    memory_types: "Memory Types",
    wattage: "Wattage",
    form_factor: "Form Factor",
    efficiency_rating: "Efficiency Rating",
    modular: "Modular",
    fanless: "Fanless",
    connectors: "Connectors",
    pcie_slots: "PCIe Slots",
    m2_slots: "M.2 Slots",
    sata_ports: "SATA Ports",
    onboard_ethernet: "Onboard Ethernet",
    wireless_networking: "Wireless Networking",
    usb_headers: "USB Headers",
    supported_motherboard_form_factors: "Supported Motherboard Form Factors",
    side_panel: "Side Panel",
    max_gpu_length_mm: "Max GPU Length (mm)",
    max_cpu_cooler_height_mm: "Max CPU Cooler Height (mm)",
    drive_bays: "Drive Bays",
    expansion_slots: "Expansion Slots",
    front_ports: "Front Ports",
    included_fans: "Included Fans",
    speed_mt_s: "Speed (MT/s)",
    modules: "Modules",
    total_capacity_gb: "Total Capacity (GB)",
    cas_latency: "CAS Latency",
    timings: "Timings",
    voltage: "Voltage",
    heat_spreader: "Heat Spreader",
    rgb: "RGB",
    capacity_gb: "Capacity (GB)",
    rpm: "RPM",
    nvme: "NVMe",
    read_speed_mb_s: "Read Speed (MB/s)",
    write_speed_mb_s: "Write Speed (MB/s)",
    size_mm: "Size (mm)",
    quantity: "Quantity",
    airflow_cfm: "Airflow (CFM)",
    noise_level_db: "Noise Level (dB)",
    pwm: "PWM",
    static_pressure_mmh2o: "Static Pressure (mmH2O)",
    water_cooled: "Water Cooled",
    radiator_size_mm: "Radiator Size (mm)",
    fan_size_mm: "Fan Size (mm)",
    sockets: "Sockets",

    // UI (Product Page)
    best_price_cash: "Best Cash Price",
    available_in_stores: "Available in {count} stores",
    go_to_store: "Go to Store",
    price_history: "Price History",
    price_history_window: "Last {days} days",
    price_history_min: "Period low:",
    price_history_empty: "Not enough data yet to show price evolution.",
    create_alert: "Create Alert",
    best_current_offer: "Best Current Offer",
    other_versions: "Other versions available",
    store_comparison: "Prices by store",
    store: "Store",
    price: "Price",
    cash: "Cash",
    normal: "Normal",
    action: "Action",
    see_offer: "See Offer",
    specs: "Specifications",
    specs_title: "Technical Specifications",
    check_stock: "Check Stock",
    in_stock: "In Stock",
    home: "Home",
    product_not_found: "Product not found",
    generic: "Generic",
    yes: "Yes",
    no: "No",

    // Preferences
    preferences: "Preferences",
    preferences_desc: "Customize your application experience.",
    visualization: "Visualization",
    choose_theme: "Choose your preferred interface.",
    system: "System",
    light: "Light",
    dark: "Dark",
    language: "Language",
    select_language: "Select interface language.",
    translation_beta_title: "Translation in beta",
    translation_beta_desc:
      "This translation is preliminary and may contain errors. Spotted something to improve? Help us by sending a suggestion.",
    suggest_correction: "Suggest a correction",
    feedback_dialog_title: "Suggest a translation correction",
    feedback_dialog_desc:
      "Pick a string and propose a better wording. Your suggestion is reviewed before being applied.",
    feedback_search_placeholder: "Search by key or text...",
    feedback_no_matches: "No matches.",
    feedback_change: "change",
    feedback_your_suggestion: "Your suggestion",
    feedback_suggestion_placeholder: "Propose a better translation...",
    feedback_comment: "Comment",
    feedback_optional: "(optional)",
    feedback_comment_placeholder: "Why is this better? Source / nuance...",
    feedback_send: "Send suggestion",
    feedback_sending: "Sending...",
    feedback_sent: "Thanks! Your suggestion was sent.",
    feedback_send_error: "Could not send feedback. Try again later.",
    feedback_empty_error: "Suggestion cannot be empty",
    feedback_same_error: "Suggestion must differ from current text",
    feedback_showing_some: "Showing 100 of {total}. Refine your search.",
    feedback_current: "current",
    feedback_empty_value: "(empty)",
    feedback_close: "Close",

    // Profile page
    profile_joined: "Joined {date}",
    profile_quotes_title_owner: "My quotes",
    profile_quotes_title_other: "{name}'s quotes",
    profile_quotes_count_owner: "{count} created quote(s)",
    profile_quotes_count_other: "{count} public quote(s)",
    profile_no_quotes_owner: "No quotes yet",
    profile_no_quotes_other: "This user has no public quotes",
    profile_no_quotes_owner_cta: "Create your first quote to start building the PC of your dreams.",
    profile_components_count: "{count} components",
    profile_default_name: "User",
    profile_back_home: "Back to home",
    profile_not_found_title: "User not found",
    profile_not_found_desc: "The profile you are looking for does not exist or has been deleted.",
    profile_load_error_title: "Error loading profile",
    profile_load_error_desc: "There was a problem loading the user's data.",
    profile_unexpected_error: "An unexpected error has occurred.",
    profile_try_again: "Please try again later.",
    profile_edit: "Edit profile",
    profile_share: "Share profile",
    profile_share_copied: "Link copied to clipboard",

    // Navbar
    explore: "Explore",
    hardware: "Hardware",
    create_quote: "Create Quote",
    search: "Search",
    user: "User",
    profile: "Profile",
    settings: "Settings",
    logout: "Log out",
    login: "Log in",
    login_desc: "Choose a provider to create your account or log in",
    continue_with: "Continue with {provider}",
    terms: "Terms",
    privacy: "Privacy",
    legal_text: "By continuing, you accept our {terms} and {privacy}",
    no_categories: "No categories available",

    // Greetings (Morning)
    greeting_morning_1: "Coffee or thermal paste for breakfast?",
    greeting_morning_2: "Prices dropped faster than you this morning",
    greeting_morning_3: "Good morning, today is the day for that CPU",
    greeting_morning_4: "Less lag and more coffee to start",
    greeting_morning_5: "The early bird gets the stock",

    // Greetings (Afternoon)
    greeting_afternoon_1: "Looking at hardware counts as work too",
    greeting_afternoon_2: "Your boss isn't looking, find that GPU",
    greeting_afternoon_3: "Another fan? Never enough",
    greeting_afternoon_4: "Hunger fades, FPS are forever",
    greeting_afternoon_5: "Just one more part and I verify I finish the build",

    // Greetings (Evening)
    greeting_evening_1: "Turn on the RGB, it's dark already",
    greeting_evening_2: "Does your PC shine brighter than your future? Mine does",
    greeting_evening_3: "Time for high FPS and low prices",
    greeting_evening_4: "It's not an expense, it's an investment in happiness",
    greeting_evening_5: "Configuring the setup to win today",

    // Greetings (Night)
    greeting_night_1: "Monitor light counts as Vitamin D",
    greeting_night_2: "Sleep is for people with slow PCs",
    greeting_night_3: "Your bank account says no, but your build says yes",
    greeting_night_4: "One eye on code, the other on that deal",
    greeting_night_5: "Tomorrow that price will be history, buy it now",

    // Home
    popular_products: "Popular Products",
    popular_products_desc: "Most viewed products by the community",
    view_all: "View all",
    no_products: "No products available",
    recent_offers: "Recent Offers",
    recent_offers_desc: "Products with price drops",

    // Add to quote
    add_to_quote: "Add to quote",
    login_to_save_quote_title: "Sign in to save",
    login_to_save_quote_desc: "Create quotes to compare PC builds and save your favorite setups.",
    select_quote: "Select quote",
    no_quotes: "You don't have created quotes",
    create_new: "Create new",
    confirm: "Confirm",
    product_added: "Product added to quote {name}",
    select_option: "Select...",

    // Create Quote Dialog
    create_new_quote_title: "Create new quote",
    create_quote_desc: "Give your project a name to start adding components.",
    create_quote_error: "Error creating quote",
    name: "Name",
    quote_name_placeholder: "Ex: PC Gamer 2026",
    description_optional: "Description (Optional)",
    quote_description_placeholder: "What will you use this PC for...",
    public_quote: "Public quote",
    cancel: "Cancel",

    // Settings Layout
    account: "Account",

    // Account Settings
    your_profile: "Your profile",
    profile_desc: "Choose how you appear as a host or guest.",
    full_name: "Full Name",
    full_name_placeholder: "Your name",
    username: "Username",
    bio_label: "Bio",
    bio_coming_soon: "Bio (Coming Soon)",
    bio_placeholder: "Share a little about your experience and interests.",
    saving: "Saving...",
    save_changes: "Save changes",
    emails: "Emails",
    emails_desc: "Manage your email addresses.",
    primary_email: "Primary email",
    managed_by_provider: "Managed by authentication provider",
    manage: "Manage",
    saving_changes_toast: "Saving changes...",
    profile_updated_toast: "Profile updated successfully",
    profile_update_error_toast: "Error updating profile",

    // Quote Details
    by: "By {name}",
    updated_on: "Updated on {date}",
    estimated_wattage: "Estimated Wattage",
    components: "Components",
    active_items_count: "{count} active",
    price_normal: "Normal Price",
    price_cash: "Cash Price",
    others: "Others",
    some_items_out_of_stock: "Some items are out of stock. Total may vary.",
    total_normal: "Total Normal",
    total_cash: "Total Cash",

    // Quote Actions / Messages
    quote_not_found: "Quote not found",
    product_removed: "Product removed",
    quote_deleted: "Quote deleted successfully",
    quote_delete_error: "Error deleting quote",
    product_added_short: "Product added",
    product_add_error: "Error adding product",
    compatibility_checked: "Compatibility checked",
    compatibility_check_error: "Error checking compatibility",
    removing_product: "Removing product...",
    remove_product_error: "Error removing product",
  },
  arn: {
    // Mapudungun (Alfabeto Mapuche Unificado). Best-effort translations:
    // technical terms are kept as Spanish/English loanwords (common practice
    // among contemporary Mapudungun speakers) while UI/action words use
    // documented Mapudungun roots. Needs review by a fluent speaker.

    // Specs
    manufacturer: "Dewmafe", // dewman = to make + -fe = agent
    chipset_manufacturer: "Chipset dewmafe",
    chipset: "Chipset",
    architecture: "Arquitectura",
    memory_gb: "Memoria (GB)",
    memory_type: "Memoria az", // az = type/manner
    core_base_clock_mhz: "Núcleo base reloj (MHz)",
    core_boost_clock_mhz: "Núcleo boost reloj (MHz)",
    core_count: "Núcleo rakin", // rakin = count
    memory_clock_mhz: "Memoria reloj (MHz)",
    memory_bus_bit: "Memoria bus (bit)",
    interface: "Interfaz",
    length_mm: "Fütran (mm)", // fütran = length
    tdp_w: "TDP (W)",
    cooling: "Wütreltun", // to cool
    slots: "Slots",
    frame_sync: "Frame sync",
    color: "Ad", // appearance
    power_connectors: "Newen conexiones", // newen = energy
    video_ports: "Video puertas",
    series: "Serie",
    microarchitecture: "Microarquitectura",
    socket: "Socket",
    cores: "Núcleos",
    clocks: "Relojes",
    cache: "Cache",
    integrated_graphics: "Gráficos integrados",
    includes_cooler: "Niey cooler", // niey = has
    ecc_support: "ECC kelluwün", // kelluwün = support
    lithography: "Litografía",
    max_memory_gb: "Doy memoria (GB)", // doy = more / max
    memory_types: "Memoria az",
    wattage: "Newen (W)",
    form_factor: "Form factor",
    efficiency_rating: "Eficiencia rating",
    modular: "Modular",
    fanless: "Ventilador nielay", // nielay = there isn't
    connectors: "Conexiones",
    pcie_slots: "PCIe slots",
    m2_slots: "M.2 slots",
    sata_ports: "SATA puertas",
    onboard_ethernet: "Ethernet integrado",
    wireless_networking: "Red wireless",
    usb_headers: "USB headers",
    supported_motherboard_form_factors: "Placa madre form factors",
    side_panel: "Inan panel",
    max_gpu_length_mm: "Doy GPU fütran (mm)",
    max_cpu_cooler_height_mm: "Doy CPU cooler fütran (mm)",
    drive_bays: "Drive bays",
    expansion_slots: "Expansión slots",
    front_ports: "Wechu puertas", // wechu = front/top
    included_fans: "Niey ventiladores",
    speed_mt_s: "Matu (MT/s)", // matu = fast
    modules: "Módulos",
    total_capacity_gb: "Kom capacidad (GB)", // kom = all/total
    cas_latency: "CAS latency",
    timings: "Timings",
    voltage: "Voltaje",
    heat_spreader: "Aren disipador", // aren = hot
    rgb: "RGB",
    capacity_gb: "Capacidad (GB)",
    rpm: "RPM",
    nvme: "NVMe",
    read_speed_mb_s: "Chillkatun matu (MB/s)", // chillkatun = to read
    write_speed_mb_s: "Wirin matu (MB/s)", // wirin = to write
    size_mm: "Fütran (mm)",
    quantity: "Rakin", // count
    airflow_cfm: "Kürüf nentun (CFM)", // kürüf = wind, nentun = movement
    noise_level_db: "Wirar (dB)", // wirar = noise
    pwm: "PWM",
    static_pressure_mmh2o: "Presión estática (mmH2O)",
    water_cooled: "Ko mew wütreltun", // ko = water, mew = with
    radiator_size_mm: "Radiador fütran (mm)",
    fan_size_mm: "Ventilador fütran (mm)",
    sockets: "Sockets",

    // UI (Product Page)
    best_price_cash: "Doy küme kullin", // doy = more/best, küme = good, kullin = pay
    available_in_stores: "Müley {count} katuwe mew", // müley = exists, katuwe = store
    go_to_store: "Amun katuwe", // amun = to go
    price_history: "Kullin kuyfi", // kuyfi = past
    price_history_window: "Inalewma {days} antü", // inalewma = last, antü = day
    price_history_min: "Doy pichi kullin:", // doy pichi = the smallest
    price_history_empty: "Petu nielay fentren dato kullin kuyfi.", // petu nielay = doesn't have yet
    create_alert: "Dewman alerta", // dewman = to make
    best_current_offer: "Doy küme oferta",
    other_versions: "Kake versiones", // kake = other
    store_comparison: "Katuwe ñi kullin", // store's price
    store: "Katuwe",
    price: "Kullin", // pay/price
    cash: "Efectivo",
    normal: "Normal",
    action: "Dewman",
    see_offer: "Pen oferta", // pen = to see
    specs: "Especificaciones",
    specs_title: "Kimün especificaciones", // kimün = knowledge
    check_stock: "Adkintun stock", // adkintun = to observe
    in_stock: "Müley",
    home: "Ruka", // house
    product_not_found: "Producto pelay", // pelay = not found
    generic: "Genérico",
    yes: "May",
    no: "Mu",

    // Preferences
    preferences: "Az dewman", // az = manner, dewman = setting
    preferences_desc: "Adkununge tami app dungun.", // adjust your app
    visualization: "Pen", // to see / view
    choose_theme: "Dullinge tami küme interfaz.", // dullin = to choose
    system: "Sistema",
    light: "Welche", // welche = light/clear (related to wel = day)
    dark: "Kurü", // kurü = black/dark
    language: "Dungun", // language/speech
    select_language: "Dullinge interfaz dungun.",
    translation_beta_title: "Traducción beta mew",
    translation_beta_desc:
      "Tüfa chi traducción doy küme dewmangelay petu. ¿Pelfimi chem küme adkünun? Kelluwaymün, küpalnge sugerencia.",
    suggest_correction: "Adkünun sugerencia",
    feedback_dialog_title: "Adkünun traducción sugerencia",
    feedback_dialog_desc: "Dullinge kiñe texto, küpalnge doy küme dungun. Adkintungeay petu adkünuael.",
    feedback_search_placeholder: "Kintunge clave kam texto mew...",
    feedback_no_matches: "Pelay.",
    feedback_change: "kake",
    feedback_your_suggestion: "Tami sugerencia",
    feedback_suggestion_placeholder: "Küpalnge doy küme traducción...",
    feedback_comment: "Nütram",
    feedback_optional: "(opcional)",
    feedback_comment_placeholder: "¿Chumechi doy küme? Fuente / nütram...",
    feedback_send: "Werkün sugerencia",
    feedback_sending: "Werküken...",
    feedback_sent: "¡Mañumtuy! Tami sugerencia werküngey.",
    feedback_send_error: "Wera werkün feedback. Wenel pengeay.",
    feedback_empty_error: "Sugerencia mu chem nielay",
    feedback_same_error: "Sugerencia kakentuy texto mew",
    feedback_showing_some: "Pengey 100 / {total}. Doy adkintunge.",
    feedback_current: "fewla",
    feedback_empty_value: "(chem nielay)",
    feedback_close: "Nürün",

    // Profile page
    profile_joined: "Konün {date} mew", // konün = entered
    profile_quotes_title_owner: "Ñi cotizaciones",
    profile_quotes_title_other: "{name} ñi cotizaciones",
    profile_quotes_count_owner: "{count} dewman cotización",
    profile_quotes_count_other: "{count} kom che cotización",
    profile_no_quotes_owner: "Cotización nielay petu",
    profile_no_quotes_other: "Tüfa che kom-che cotización nielay",
    profile_no_quotes_owner_cta: "Dewmange tami wüne cotización, küduwüstuaymi tami PC.",
    profile_components_count: "{count} componentes",
    profile_default_name: "Che",
    profile_back_home: "Wüñoltuy ruka mew",
    profile_not_found_title: "Che pelay",
    profile_not_found_desc: "Tati che kintunelu nielay kam entuy.",
    profile_load_error_title: "Wera che dungun",
    profile_load_error_desc: "Müley wera kintun che dungun mew.",
    profile_unexpected_error: "Wera dungun tripay.",
    profile_try_again: "Wenel pengeay.",
    profile_edit: "Adkünun che",
    profile_share: "Wüllelu che",
    profile_share_copied: "Link wülley portapapeles mew",

    // Navbar
    explore: "Inarumen", // to explore
    hardware: "Hardware",
    create_quote: "Dewman cotización",
    search: "Kintun", // to search
    user: "Che", // person
    profile: "Tami che", // your person/profile
    settings: "Az dewman", // settings
    logout: "Tripan", // to leave
    login: "Konun", // to enter
    login_desc: "Dullinge proveedor mew tami konual kam dewmayal cuenta", // choose provider to log in or create account
    continue_with: "Inangepe {provider} mew", // continue with
    terms: "Términos",
    privacy: "Privacidad",
    legal_text: "Inangelu, feyentukunge tati {terms} ka {privacy}", // by continuing you accept terms and privacy
    no_categories: "Categorías nielay", // there aren't categories

    // Greetings (Morning) — wün = morning
    greeting_morning_1: "¿Kafe kam pasta térmica wünmay?", // coffee or thermal paste for breakfast
    greeting_morning_2: "Tati kullin doy matu nag-i, eymi tami umaq mew doy", // prices fell faster than you from bed
    greeting_morning_3: "Mari mari, fachi antü tripayay tati procesador", // hello, today that processor will come out
    greeting_morning_4: "Pichi lag, doy kafe wüne", // less lag, more coffee first
    greeting_morning_5: "Tati wüne küpalu, niey tati stock", // the one who comes first, has the stock

    // Greetings (Afternoon) — rangiantü = midday
    greeting_afternoon_1: "Hardware adkintun küdaw rakingey", // looking at hardware counts as work
    greeting_afternoon_2: "Tami jefe pelay, kintunge tati GPU", // your boss isn't looking, search that GPU
    greeting_afternoon_3: "Ka ventilador? Mülenmu rume", // another fan? never enough
    greeting_afternoon_4: "Niwün rupay, FPS rumel mülen", // hunger passes, FPS stays forever
    greeting_afternoon_5: "Kiñe ka pieza, ka feyentukey af-küduwan", // one more part, and I'll really finish the build

    // Greetings (Evening) — naqantü = sunset
    greeting_evening_1: "Üyumtulnge RGB, kuruley ka", // turn on the RGB, it's already dark
    greeting_evening_2: "¿Tami PC doy alof tami küpalniey mew? Iñche may", // does your PC shine more than your future? Mine yes
    greeting_evening_3: "Doy FPS ka pichi kullin antü", // more FPS and lower price time
    greeting_evening_4: "Mu kütral kullin, küme inversión kümelkalen mew", // not a waste, good investment in happiness
    greeting_evening_5: "Setup adkununiel weñagke fachi antü", // configuring setup to win today

    // Greetings (Night) — pun = night
    greeting_night_1: "Tati monitor pelon vitamina D rakingey", // monitor light counts as vitamin D
    greeting_night_2: "Umautun tati pichi newen PC niefilu mew", // sleep is for those who have slow PCs
    greeting_night_3: "Tami banco mu pi, welu tami build may pi", // your bank says no, but your build says yes
    greeting_night_4: "Kiñe nge code mew, ka oferta mew", // one eye on code, one on the offer
    greeting_night_5: "Wüle tati kullin nütram-ngeay, ngillange ka", // tomorrow that price will be history, buy it already

    // Home
    popular_products: "Doy pen productos", // most-seen products
    popular_products_desc: "Tati doy pen productos kom che mew",
    view_all: "Pen kom", // see all
    no_products: "Productos nielay", // no products
    recent_offers: "We ofertas", // we = new
    recent_offers_desc: "Kullin nag-i productos", // products with price down

    // Add to quote
    add_to_quote: "Yengen cotización mew", // add to quote
    login_to_save_quote_title: "Konunge tami elkayal", // konunge = enter, elkayal = save
    login_to_save_quote_desc: "Dewmayal cotizaciones tami müñetuyal PCs ka elkayal tami doy küme armado.", // make to compare and save
    select_quote: "Dullinge cotización",
    no_quotes: "Cotizaciones nielay", // no quotes
    create_new: "Dewman we", // create new
    confirm: "Feyentun", // to agree/accept
    product_added: "Producto yengey {name} cotización mew",
    select_option: "Dullinge...", // choose

    // Create Quote Dialog
    create_new_quote_title: "Dewman we cotización",
    create_quote_desc: "Elungue üy tami proyecto, küduwüstuaymi componentes.", // give name to project, you'll add components
    create_quote_error: "Wera dewman cotización", // wera = bad
    name: "Üy",
    quote_name_placeholder: "Ej: PC Gamer 2026",
    description_optional: "Nütram (Opcional)", // nütram = description/story
    quote_description_placeholder: "Chem mew küduwaymi PC...", // for what you'll use the PC
    public_quote: "Kom che cotización", // all-people quote (public)
    cancel: "Katrütun", // to stop

    // Settings Layout
    account: "Cuenta",

    // Account Settings
    your_profile: "Tami che", // your person
    profile_desc: "Dullinge chumechi pengey eymi anfitrión kam invitado.", // choose how you appear
    full_name: "Kom üy", // full name
    full_name_placeholder: "Tami üy",
    username: "Üy",
    bio_label: "Nütram",
    bio_coming_soon: "Bio (küpalealu)", // coming
    bio_placeholder: "Nütramnge tami nütram ka tami ayikelu.", // tell your story and what you like
    saving: "Elkünuken...", // saving
    save_changes: "Elkünunge cambios", // save changes
    emails: "Emails",
    emails_desc: "Adkintunge tami emails", // observe / manage your emails
    primary_email: "Wüne email", // primary
    managed_by_provider: "Adkintungey proveedor mew", // managed by provider
    manage: "Adkintun", // observe / manage
    saving_changes_toast: "Elkünuken cambios...",
    profile_updated_toast: "Tami che adkünungey küme", // your profile was updated well
    profile_update_error_toast: "Wera adkünun tami che",

    // Quote Details
    by: "Kelu {name}", // kelu = by/from
    updated_on: "Adkünungey {date}", // updated on
    estimated_wattage: "Newen rakin", // energy count
    components: "Componentes",
    active_items_count: "{count} mongey", // mongey = alive/active
    price_normal: "Kullin normal",
    price_cash: "Kullin efectivo",
    others: "Kake", // others
    some_items_out_of_stock: "Kiñeke productos stock nielay. Total kakey.", // some products no stock. Total varies
    total_normal: "Kom normal",
    total_cash: "Kom efectivo",

    // Quote Actions / Messages
    quote_not_found: "Cotización pelay", // not found
    product_removed: "Producto entutuy", // removed
    quote_deleted: "Cotización entutuy",
    quote_delete_error: "Wera entutun cotización",
    product_added_short: "Producto yengey",
    product_add_error: "Wera yengen producto",
    compatibility_checked: "Compatibilidad adkintungey",
    compatibility_check_error: "Wera adkintun compatibilidad",
    removing_product: "Entutuken producto...", // removing
    remove_product_error: "Wera entutun producto",
  },
};

export const getTranslation = (lang: Lang = "es", key: string, params?: Record<string, string | number>) => {
  let text = dictionaries[lang]?.[key] || dictionaries.es[key] || key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{${k}}`, String(v));
    }
  }
  return text;
};
